export enum IconList {
  Housing = 'home',
  Transportation = 'train-car',
  Food = 'food',
  Entertainment = 'movie-edit',
  Clothing = 'hanger',
  Health = 'bottle-tonic-plus',
  Education = 'school',
  GiftsDonation = 'gift',
  Search = 'magnify',
  Type = 'format-list-bulleted-type',
  Category = 'shape',
  Date = 'clipboard-text-clock-outline',
  Amount = 'currency-rupee',
  Description = 'order-bool-descending',
  PersonalCare = 'doctor',
}
